name: Frontend Deployment
on:
  push:
    branches: [Prod]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build frontend
        run: npm run build
      - name: PWD
        run: pwd
      - name: Do LS
        run: ls
      # - name: CD Dist
      #   run: sudo chmod -R 755 /home/runner/work/tbrFrontend/tbrFrontend/src
      - name: cat file
        run: cat /home/runner/work/tbrFrontend/tbrFrontend/index.html
      - name: PWD II
        run: pwd
      - name: Do LS II
        run: ls
      - name: SCP dist to ec2
        run: scp -r ${{ secrets.SSH_PRIVATE_KEY }} /home/runner/work/tbrFrontend/tbrFrontend/dist ec2-user@${{ secrets.HOSTNAME }}:/home/ec2-user/frontend
      - name: Deploy to EC2 using SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ec2-user/frontend
            sudo systemctl stop nginx
            sudo systemctl restart nginx
              '
